version: "3"

networks:
    traefik-net:
      external: true

volumes:
    data:

services:

    nginx:
      image: nginx
      networks:
        - traefik-net
      volumes:
        - ./src:/usr/share/nginx/html
      restart: always
      deploy:
        labels:
          - "traefik.port=80"
          - "traefik.docker.network=traefik-net"
          - "traefik.backend=e_nginx"
          - "traefik.frontend.priority=20"
          - "traefik.frontend.rule=PathPrefix:/home/images,/rubarcode/images,/rotcs/images,/km/images"
          - "traefik.backend.loadbalancer.sticky=true"

    php7:
      image: php7-prod
      networks:
        - traefik-net
      volumes:
        - ./src:/var/www/html
        - ./conf/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini
      depends_on:
        - mysql
      restart: always
      deploy:
        labels:
          - "traefik.port=80"
          - "traefik.docker.network=traefik-net"
          - "traefik.backend=e_php7"
          - "traefik.frontend.priority=10"
          - "traefik.frontend.rule=PathPrefix:/MyAdmin,/rotcs"
          - "traefik.backend.loadbalancer.sticky=true"

    php56:
      image: php56-prod
      networks:
        - traefik-net
      volumes:
        - ./src:/var/www/html
        - ./conf/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini
      depends_on:
        - mysql
      restart: always
      deploy:
        labels:
          - "traefik.port=80"
          - "traefik.docker.network=traefik-net"
          - "traefik.backend=e_php56"
          - "traefik.frontend.priority=10"
          - "traefik.frontend.rule=PathPrefix:/home,/rubarcode,/procurement,/km"
          - "traefik.backend.loadbalancer.sticky=true"

    mysql:
      image: mysql-prod
      networks:
        - traefik-net
      volumes:
        - ./build/mysql:/docker-entrypoint-initdb.d
        - ./build/mysql/my-cron:/etc/cron.d/my-cron
        - ./tmp/mysql:/var/lib/mysql
        - ./conf/oracle/tnsnames.ora:/usr/local/instantclient/tnsnames.ora
        - ./conf/my.cnf:/etc/mysql/my.cnf
        - ./database:/database
      ports:
        - 3306:3306
      restart: always
      environment:
        - MYSQL_DATABASE=world
        - MYSQL_ROOT_PASSWORD=Db4Admin4

    traefik:
      image: traefik
      command: -c /dev/null --web --docker --docker.swarmmode --docker.watch --docker.domain=traefik --logLevel=DEBUG
      networks:
        - traefik-net
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik.toml:/etc/traefik/traefik.toml
      deploy:
        placement:
          constraints: [node.role == manager]
